export const POST_BUG_REPORTS_REQUEST = 'POST_BUG_REPORTS_REQUEST';
export const POST_BUG_REPORTS_SUCCESS = 'POST_BUG_REPORTS_SUCCESS';
export const POST_BUG_REPORTS_FAILURE = 'POST_BUG_REPORTS_FAILURE';

export const GET_ALL_REPORTS_BUG_REQUEST = 'GET_ALL_REPORTS_BUG_REQUEST';
export const GET_ALL_REPORTS_BUG_SUCCESS = 'GET_ALL_REPORTS_BUG_SUCCESS';
export const GET_ALL_REPORTS_BUG_FAILURE = 'GET_ALL_REPORTS_BUG_FAILURE';

export const GET_ALL_REPORTS_BUG_USER_SIDE_REQUEST =
  'GET_ALL_REPORTS_BUG_USER_SIDE_REQUEST';
export const GET_ALL_REPORTS_BUG_USER_SIDE_SUCCESS =
  'GET_ALL_REPORTS_BUG_USER_SIDE_SUCCESS';
export const GET_ALL_REPORTS_BUG_USER_SIDE_FAILURE =
  'GET_ALL_REPORTS_BUG_USER_SIDE_FAILURE';
