export const POST_BUG_REPORTS_REQUEST = 'POST_BUG_REPORTS_REQUEST';
export const POST_BUG_REPORTS_SUCCESS = 'POST_BUG_REPORTS_SUCCESS';
export const POST_BUG_REPORTS_FAILURE = 'POST_BUG_REPORTS_FAILURE';
