export const REGISTER_WITH_EMAIL_REQUEST = 'REGISTER_WITH_EMAIL_REQUEST';
export const REGISTER_WITH_EMAIL_SUCCESS = 'REGISTER_WITH_EMAIL_SUCCESS';
export const REGISTER_WITH_EMAIL_FAILURE = 'REGISTER_WITH_EMAIL_FAILURE';

export const REGISTER_WITH_GOOGLE_REQUEST = 'REGISTER_WITH_GOOGLE_REQUEST';
export const REGISTER_WITH_GOOGLE_FAILURE = 'REGISTER_WITH_GOOGLE_FAILURE';
export const REGISTER_WITH_GOOGLE_SUCCESS = 'REGISTER_WITH_GOOGLE_SUCCESS';

export const CREATE_USER_ROLE_REQUEST = 'CREATE_USER_ROLE_REQUEST';
export const CREATE_USER_ROLE_SUCCESS = 'CREATE_USER_ROLE_SUCCESS';
export const CREATE_USER_ROLE_FAILURE = 'CREATE_USER_ROLE_FAILURE';

export const GET_USER_ROLE_REQUEST = 'GET_USER_ROLE_REQUEST';
export const GET_USER_ROLE_SUCCESS = 'GET_USER_ROLE_SUCCESS';
export const GET_USER_ROLE_FAILURE = 'GET_USER_ROLE_FAILURE';

export const GET_ALL_USERS_REQUEST = 'GET_ALL_USERS_REQUEST';
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const GET_ALL_USERS_FAILURE = 'GET_ALL_USERS_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
