export const REGISTER_WITH_EMAIL_REQUEST = 'REGISTER_WITH_EMAIL_REQUEST';
export const REGISTER_WITH_EMAIL_SUCCESS = 'REGISTER_WITH_EMAIL_SUCCESS';
export const REGISTER_WITH_EMAIL_FAILURE = 'REGISTER_WITH_EMAIL_FAILURE';

export const REGISTER_WITH_GOOGLE_REQUEST = 'REGISTER_WITH_GOOGLE_REQUEST';
export const REGISTER_WITH_GOOGLE_FAILURE = 'REGISTER_WITH_GOOGLE_FAILURE';
export const REGISTER_WITH_GOOGLE_SUCCESS = 'REGISTER_WITH_GOOGLE_SUCCESS';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
