export const GET_UPCOMMING_MOVIES_REQUEST = 'GET_UPCOMMING_MOVIES_REQUEST';
export const GET_UPCOMMING_MOVIES_SUCCESS = 'GET_UPCOMMING_MOVIES_SUCCESS';
export const GET_UPCOMMING_MOVIES_FAILURE = 'GET_UPCOMMING_MOVIES_FAILURE';

export const GET_RELESE_MOVIES_REQUEST = 'GET_RELESE_MOVIES_REQUEST';
export const GET_RELESE_MOVIES_SUCCESS = 'GET_RELESE_MOVIES_SUCCESS';
export const GET_RELESE_MOVIES_FAILURE = 'GET_RELESE_MOVIES_FAILURE';

export const GET_MOVIES_TRENDING_REQUEST = 'GET_MOVIES_TRENDING_REQUEST';
export const GET_MOVIES_TRENDING_SUCCESS = 'GET_MOVIES_TRENDING_SUCCESS';
export const GET_MOVIES_TRENDING_FAILURE = 'GET_MOVIES_TRENDING_FAILURE';

export const GET_MOVIES_TOP_RETED_REQUEST = 'GET_MOVIES_TOP_RETED_REQUEST';
export const GET_MOVIES_TOP_RETED_SUCCESS = 'GET_MOVIES_TOP_RETED_SUCCESS';
export const GET_MOVIES_TOP_RETED_FAILURE = 'GET_MOVIES_TOP_RETED_FAILURE';

export const GET_MOVIES_BY_ID_REQUEST = 'GET_MOVIES_BY_ID_REQUEST';
export const GET_MOVIES_BY_ID_SUCCESS = 'GET_MOVIES_BY_ID_SUCCESS';
export const GET_MOVIES_BY_ID_FAILURE = 'GET_MOVIES_BY_ID_FAILURE';

export const SEARCH_MOVIES_REQUEST = 'SEARCH_MOVIES_REQUEST';
export const SEARCH_MOVIES_SUCCESS = 'SEARCH_MOVIES_SUCCESS';
export const SEARCH_MOVIES_FAILURE = 'SEARCH_MOVIES_FAILURE';

export const GET_GENRES_REQUEST = 'GET_GENRES_REQUEST';
export const GET_GENRES_SUCCESS = 'GET_GENRES_SUCCESS';
export const GET_GENRES_FAILURE = 'GET_GENRES_FAILURE';

export const GET_MOVIES_BY_GENRE_REQUEST = 'GET_MOVIES_BY_GENRE_REQUEST';
export const GET_MOVIES_BY_GENRE_SUCCESS = 'GET_MOVIES_BY_GENRE_SUCCESS';
export const GET_MOVIES_BY_GENRE_FAILURE = 'GET_MOVIES_BY_GENRE_FAILURE';

export const GET_TRAILER_REQUEST = 'GET_TRAILER_REQUEST';
export const GET_TRAILER_SUCCESS = 'GET_TRAILER_SUCCESS';
export const GET_TRAILER_FAILURE = 'GET_TRAILER_FAILURE';
